"""
Test script for Phase 5: AI-powered insights generation
Tests both Gemini AI and rule-based fallback modes.
"""

from pathlib import Path
import sys

# Add project root to path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

from app.services.video_analysis import VideoAnalysisService
import json


def test_ai_insights_with_gemini(api_key: str = None):
    """Test AI insights with Gemini API."""
    print("=" * 80)
    print("Test 1: AI Insights with Google Gemini")
    print("=" * 80)
    
    # Use sample video
    video_path = project_root / "sample_video.mp4"
    
    if not video_path.exists():
        print(f"❌ Sample video not found: {video_path}")
        print("Please place a video at sample_video.mp4")
        return
    
    print(f"\n📹 Analyzing video: {video_path.name}")
    print(f"🤖 AI insights: Enabled")
    print(f"🔑 API key: {'Provided' if api_key else 'From environment'}")
    print()
    
    # Create service with AI insights enabled
    service = VideoAnalysisService(
        frame_sample_rate=30,
        confidence_threshold=0.5,
        enable_ai_insights=True,
        gemini_api_key=api_key
    )
    
    # Progress callback
    def progress(current, total, message):
        print(f"[{current:3d}%] {message}")
    
    # Run analysis
    results = service.analyze_video(
        video_path=video_path,
        progress_callback=progress,
        save_detections=False
    )
    
    # Display results
    if results.get("status") == "completed":
        print("\n" + "=" * 80)
        print("✅ ANALYSIS COMPLETE")
        print("=" * 80)
        
        # Basic statistics
        stats = results.get("statistics", {})
        print(f"\n📊 Statistics:")
        print(f"   - Average people: {stats.get('average_person_count', 0):.1f}")
        print(f"   - Peak count: {stats.get('max_person_count', 0)}")
        print(f"   - Crowd level: {results.get('insights', {}).get('crowd_level', 'N/A')}")
        
        # AI Insights
        ai_insights = results.get("ai_insights", {})
        if ai_insights and not ai_insights.get("error"):
            print("\n" + "=" * 80)
            print("🤖 AI-POWERED INSIGHTS")
            print("=" * 80)
            print(f"Generated by: {ai_insights.get('generated_by', 'unknown')}")
            print(f"Generated at: {ai_insights.get('generated_at', 'unknown')}")
            
            # Summary
            print("\n📝 Executive Summary:")
            print(f"   {ai_insights.get('ai_summary', 'N/A')[:500]}")
            
            # Key Findings
            findings = ai_insights.get('key_findings', [])
            if findings:
                print(f"\n🔍 Key Findings ({len(findings)}):")
                for i, finding in enumerate(findings[:5], 1):
                    print(f"   {i}. {finding}")
            
            # Staff Recommendations
            staff = ai_insights.get('staff_suggestions', {})
            if staff:
                print(f"\n👥 Staff Recommendations:")
                print(f"   - Suggested nurses: {staff.get('suggested_nurses', 0)}")
                print(f"   - Reasoning: {staff.get('reasoning', 'N/A')[:200]}")
            
            # Bottleneck Areas
            bottlenecks = ai_insights.get('bottleneck_areas', [])
            if bottlenecks:
                print(f"\n⚠️  Bottleneck Areas ({len(bottlenecks)}):")
                for i, area in enumerate(bottlenecks[:3], 1):
                    print(f"   {i}. {area}")
            
            # Priority Actions
            actions = ai_insights.get('priority_actions', [])
            if actions:
                print(f"\n🎯 Priority Actions ({len(actions)}):")
                for i, action in enumerate(actions[:5], 1):
                    print(f"   {i}. {action}")
            
            # Recommendations
            recommendations = ai_insights.get('recommendations', [])
            if recommendations:
                print(f"\n💡 Recommendations ({len(recommendations)}):")
                for i, rec in enumerate(recommendations[:5], 1):
                    print(f"   {i}. {rec}")
            
            print("\n" + "=" * 80)
        else:
            error_msg = ai_insights.get("error") or ai_insights.get("message", "Unknown error")
            print(f"\n⚠️  AI Insights Error: {error_msg}")
            print("Falling back to rule-based insights...")
    else:
        print(f"\n❌ Analysis failed: {results.get('error', 'Unknown error')}")
    
    print("\n" + "=" * 80 + "\n")


def test_rule_based_insights():
    """Test rule-based insights (no API key)."""
    print("=" * 80)
    print("Test 2: Rule-Based Insights (No API Key)")
    print("=" * 80)
    
    # Use sample video
    video_path = project_root / "sample_video.mp4"
    
    if not video_path.exists():
        print(f"❌ Sample video not found: {video_path}")
        return
    
    print(f"\n📹 Analyzing video: {video_path.name}")
    print(f"🤖 AI insights: Enabled (will fallback to rule-based)")
    print(f"🔑 API key: None (testing fallback)")
    print()
    
    # Create service with AI enabled but no API key
    service = VideoAnalysisService(
        frame_sample_rate=30,
        confidence_threshold=0.5,
        enable_ai_insights=True,
        gemini_api_key=None  # Force rule-based
    )
    
    # Progress callback
    def progress(current, total, message):
        print(f"[{current:3d}%] {message}")
    
    # Run analysis
    results = service.analyze_video(
        video_path=video_path,
        progress_callback=progress,
        save_detections=False
    )
    
    # Display AI insights
    if results.get("status") == "completed":
        ai_insights = results.get("ai_insights", {})
        if ai_insights:
            print("\n" + "=" * 80)
            print("🔧 RULE-BASED INSIGHTS")
            print("=" * 80)
            print(f"Generated by: {ai_insights.get('generated_by', 'unknown')}")
            
            print(f"\n📝 Summary: {ai_insights.get('ai_summary', 'N/A')[:300]}")
            
            findings = ai_insights.get('key_findings', [])
            print(f"\n🔍 Key Findings: {len(findings)}")
            for i, f in enumerate(findings[:3], 1):
                print(f"   {i}. {f}")
            
            print("\n✅ Rule-based fallback working correctly!")
            print("=" * 80)
    
    print("\n" + "=" * 80 + "\n")


def test_disabled_insights():
    """Test with AI insights disabled."""
    print("=" * 80)
    print("Test 3: AI Insights Disabled")
    print("=" * 80)
    
    video_path = project_root / "sample_video.mp4"
    
    if not video_path.exists():
        print(f"❌ Sample video not found: {video_path}")
        return
    
    print(f"\n📹 Analyzing video: {video_path.name}")
    print(f"🤖 AI insights: Disabled")
    print()
    
    # Create service with AI disabled
    service = VideoAnalysisService(
        frame_sample_rate=30,
        confidence_threshold=0.5,
        enable_ai_insights=False
    )
    
    # Progress callback
    def progress(current, total, message):
        print(f"[{current:3d}%] {message}")
    
    # Run analysis
    results = service.analyze_video(
        video_path=video_path,
        progress_callback=progress,
        save_detections=False
    )
    
    if results.get("status") == "completed":
        has_ai = "ai_insights" in results
        print(f"\n{'❌' if has_ai else '✅'} AI insights {'present (unexpected)' if has_ai else 'not present (expected)'}")
        print("=" * 80)
    
    print("\n" + "=" * 80 + "\n")


def main():
    """Run all tests."""
    print("\n" + "=" * 80)
    print(" PHASE 5: AI-POWERED INSIGHTS TEST SUITE")
    print("=" * 80 + "\n")
    
    # Check for API key
    import os
    api_key = os.getenv("GEMINI_API_KEY")
    
    if api_key:
        print("✅ GEMINI_API_KEY found in environment")
        print(f"   Key: {api_key[:10]}...{api_key[-4:]}" if len(api_key) > 14 else "   Key: [REDACTED]")
    else:
        print("⚠️  GEMINI_API_KEY not found in environment")
        print("   AI will use rule-based fallback mode")
    
    print("\n" + "-" * 80 + "\n")
    
    # Test 1: With Gemini API (if available)
    if api_key:
        test_ai_insights_with_gemini(api_key)
    else:
        print("⏭️  Skipping Test 1 (no API key)")
        print()
    
    # Test 2: Rule-based fallback
    test_rule_based_insights()
    
    # Test 3: Disabled
    test_disabled_insights()
    
    print("\n" + "=" * 80)
    print(" ALL TESTS COMPLETE")
    print("=" * 80 + "\n")
    
    if not api_key:
        print("💡 TIP: Set GEMINI_API_KEY environment variable to test Gemini AI mode")
        print("   Get your key from: https://makersuite.google.com/app/apikey")
        print()


if __name__ == "__main__":
    main()
