"""
Test Chat Enhancement - Demonstrates improved responses
Run this to see the dynamic chat in action
"""

from app.services.chat_assistant import ChatAssistant
import json

# Sample analysis results (what gets passed from video analysis)
SAMPLE_ANALYSIS = {
    "video_metadata": {
        "filename": "test_video.mp4",
        "duration_formatted": "5 minutes 30 seconds"
    },
    "statistics": {
        "frames_analyzed": 330,
        "average_person_count": 45.2,
        "max_person_count": 87,
        "total_detections": 14850
    },
    "insights": {
        "crowd_level": "High",
        "suggested_nurses": 5,
        "peak_congestion_time": "02:45 (2:45 PM)",
        "is_safe": False
    },
    "enhanced_analytics": {
        "crowd_density": {
            "density_level": "High",
            "density_per_sqm": 1.45,
            "severity_score": 4.2
        },
        "bottleneck_analysis": {
            "bottlenecks_detected": 3,
            "severity_level": "High",
            "total_duration_seconds": 180
        },
        "spatial_distribution": {
            "distribution_pattern": "Clustered",
            "hotspots": [
                {"zone": "Reception Area", "density": 1.8},
                {"zone": "Waiting Chairs", "density": 1.2},
                {"zone": "Hallway", "density": 0.9}
            ]
        },
        "flow_metrics": {
            "trend": "Increasing",
            "flow_rate": 0.42
        }
    },
    "ai_insights": {
        "error": False,
        "ai_summary": "High crowd density with sustained bottlenecks in reception area."
    }
}

# Test questions that were failing before
TEST_QUESTIONS = [
    "When was the crowd highest?",
    "How much recommended nurses",
    "The pople it too much how",
    "How if nurses nothing left again",
    "Hi",
    "What should we do about bottlenecks?",
    "Can you explain the density?",
    "Why do you recommend 5 nurses?"
]

def test_chat_responses():
    """Test the enhanced chat assistant"""
    
    print("\n" + "="*80)
    print("🤖 CHAT ASSISTANT ENHANCEMENT TEST")
    print("="*80)
    
    # Initialize chat assistant (rule-based mode)
    chat = ChatAssistant()
    
    # Start conversation with analysis
    print("\n[STARTING CONVERSATION]")
    result = chat.start_conversation(SAMPLE_ANALYSIS)
    print(f"Assistant: {result}\n")
    
    # Test each question
    for i, question in enumerate(TEST_QUESTIONS, 1):
        print(f"\n{'─'*80}")
        print(f"Test {i}: User Question")
        print(f"{'─'*80}")
        print(f"📝 User: \"{question}\"")
        
        # Get response
        response_data = chat.send_message(question, conversation_history=[])
        
        # Display response
        print(f"\n🤖 Assistant: {response_data['response']}")
        
        # Display metadata
        print(f"\n📊 Response Metadata:")
        print(f"   - Generated by: {response_data['generated_by']}")
        print(f"   - Matched keywords: {response_data.get('matched_keywords', [])}")
        print(f"   - Timestamp: {response_data['timestamp']}")
    
    # Print summary
    print(f"\n{'='*80}")
    print("✅ ALL TESTS COMPLETED")
    print(f"{'='*80}\n")

def compare_responses():
    """Compare before and after responses"""
    
    print("\n" + "="*80)
    print("📊 BEFORE vs AFTER COMPARISON")
    print("="*80)
    
    chat = ChatAssistant()
    chat.start_conversation(SAMPLE_ANALYSIS)
    
    test_cases = [
        ("When was the crowd highest?", "Timing question"),
        ("How much recommended nurses", "Staff recommendation"),
        ("The pople it too much how", "Vague question with typo"),
    ]
    
    for question, description in test_cases:
        print(f"\n{'─'*80}")
        print(f"📌 {description}")
        print(f"{'─'*80}")
        print(f"Question: \"{question}\"")
        
        response = chat.send_message(question)
        
        print(f"\n✅ NEW RESPONSE (Dynamic):")
        # Format response for readability
        lines = response['response'].split('\n')
        for line in lines:
            print(f"   {line}")
        
        print(f"\nMatched Keywords: {response.get('matched_keywords', [])}")

def show_data_extraction():
    """Show what data gets extracted for responses"""
    
    print("\n" + "="*80)
    print("🔍 DATA EXTRACTION FOR DYNAMIC RESPONSES")
    print("="*80)
    
    chat = ChatAssistant()
    chat.start_conversation(SAMPLE_ANALYSIS)
    
    print("\n📊 Extracted and Cached Data:")
    print(f"   avg_people: {chat.avg_people:.0f} people")
    print(f"   max_people: {chat.max_people} people")
    print(f"   suggested_nurses: {chat.suggested_nurses} nurses")
    print(f"   peak_time: {chat.peak_time}")
    print(f"   density_level: {chat.density_level}")
    print(f"   density_per_sqm: {chat.density_per_sqm:.2f}")
    print(f"   bottleneck_count: {chat.bottleneck_count}")
    print(f"   bottleneck_severity: {chat.bottleneck_severity}")
    print(f"   bottleneck_duration: {chat.bottleneck_duration} seconds")
    print(f"   hotspots: {len(chat.hotspots)} zones")
    
    print("\n💡 This data is used in EVERY response for context")

if __name__ == "__main__":
    # Run tests
    test_chat_responses()
    compare_responses()
    show_data_extraction()
    
    print("\n" + "="*80)
    print("🎉 Chat Enhancement Verification Complete!")
    print("="*80)
    print("\n✅ Chat assistant now:")
    print("   - Understands vague questions")
    print("   - Uses real data from analysis")
    print("   - Provides specific, actionable answers")
    print("   - Handles informal input")
    print("   - Gives context-aware responses")
    print("\n🚀 Ready for production deployment!")
    print("="*80 + "\n")
